# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::PlayerInputType`.
# Please instead update this file by running `bin/tapioca dsl Types::PlayerInputType`.

class Types::PlayerInputType
  sig { returns(::String) }
  def first_name; end

  sig { returns(::String) }
  def last_name; end
end
