apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    zone: dev
    version: v1
spec:
  containers:
    - name: db-ctr
      image: mongo
      ports:
        - containerPort: 27017
    - name: api-ctr
      image: alexiscrack3/spinny-api:latest
      ports:
        - containerPort: 3000
