apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: spinny-label
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30001
      protocol: TCP
  selector:
    app: spinny-label
