inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  UseCache: true
  CacheRootDirectory: tmp/rubocop
  Exclude:
    - db/schema.rb
    - bin/*
    - config/**/*
    - lib/*

Style/MethodCallWithArgsParentheses:
  Enabled: false
