version: "3.8"

services:
  api:
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    ports:
      - 3000:3000
    networks:
      - app-network
      - data-network

  db:
    image: mysql:5.7.37
    platform: linux/x86_64
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - data-network
    volumes:
      - data-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      # interval: 1m30s
      timeout: 30s
      retries: 5
      # start_period: 30s

  redis:
    image: redis:7.0.7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-volume:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:8081"
    networks:
      - data-network

networks:
  app-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
  redis-volume:
    driver: local
