version: "3"

services:
    api:
        container_name: api
        env_file: .env
        environment:
            MONGO_HOSTNAME: db
        depends_on:
            - db
        ports:
            - "3000:3000"
            # - "3000-3010:3000"
        networks:
            - spinny-network
    db:
        image: mongo
        container_name: db
        ports:
            - "27017:27017"
        networks:
            - spinny-network
        volumes:
            - spinny-volume:/data/db
    web:
        image: alexiscrack3/spinny-react:latest
        container_name: web
        depends_on:
            - api
        ports:
            - "80:80"
        networks:
            - spinny-network

networks:
    spinny-network:
        driver: bridge

volumes:
  spinny-volume:
