version: "3.8"

services:
  api:
    container_name: api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    ports:
      - 3000:3000
    networks:
      - api-network
      - data-network

  db:
    image: mysql:5.7.37
    platform: linux/x86_64
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - data-network
    volumes:
      - data-volume:/var/lib/mysql

networks:
  api-network:
    driver: bridge
  data-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
