# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WelcomeJob`.
# Please instead update this file by running `bin/tapioca dsl WelcomeJob`.

class WelcomeJob
  class << self
    sig { params(args: T.untyped).returns(T.any(WelcomeJob, FalseClass)) }
    def perform_later(*args); end

    sig { params(args: T.untyped).returns(T.untyped) }
    def perform_now(*args); end
  end
end
