# frozen_string_literal: true
# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::DEBUGGER__::TrapInterceptor; end
module Mocha::Mock; end
module Sidekiq::Process; end
module Sidekiq::SortedEntry; end
module Sidekiq::Web; end
